function run_spm_lsa(config_path, smoothing_fwhm_mm, output_dir)
% Historical-style SPM LS-A for one Subject 4 space/smoothing setup.
%
% The input configuration is generated by prepare_spm_branch.py. The output
% directory must not exist or must be empty. Smoothing is applied to every BOLD
% volume before GLM estimation, as proven by the historical Subject 4 SPM.mat.

if nargin ~= 3
    error('Usage: run_spm_lsa(config_path, smoothing_fwhm_mm, output_dir)');
end
if ~isscalar(smoothing_fwhm_mm) || ~ismember(smoothing_fwhm_mm, [0 3 5 8])
    error('smoothing_fwhm_mm must be one of 0, 3, 5, or 8');
end
if ~isfile(config_path)
    error('Configuration does not exist: %s', config_path);
end
if isfolder(output_dir) && ~isempty(dir(fullfile(output_dir, '*')))
    listing = dir(fullfile(output_dir, '*'));
    listing = listing(~ismember({listing.name}, {'.', '..'}));
    if ~isempty(listing)
        error('Refusing to overwrite non-empty output directory: %s', output_dir);
    end
end
if ~isfolder(output_dir), mkdir(output_dir); end

spm('defaults', 'FMRI');
spm_jobman('initcfg');
config = jsondecode(fileread(config_path));
if config.subject ~= 4 || numel(config.runs) ~= 10
    error('Configuration is not the frozen Subject 4 ten-run design');
end

input_dir = fullfile(output_dir, 'model_inputs');
if ~isfolder(input_dir), mkdir(input_dir); end
scan_lists = cell(1, 10);

for run_index = 1:10
    source = config.runs(run_index).bold_nii;
    if ~isfile(source), error('Missing BOLD input: %s', source); end
    if smoothing_fwhm_mm == 0
        model_input = source;
    else
        model_input = fullfile(input_dir, sprintf('run-%02d_s%gmm_bold.nii', run_index, smoothing_fwhm_mm));
        if isfile(model_input)
            error('Refusing to reuse unverified smoothed input: %s', model_input);
        end
        fprintf('SPM smoothing run %02d at %g mm FWHM\n', run_index, smoothing_fwhm_mm);
        spm_smooth(source, model_input, [smoothing_fwhm_mm smoothing_fwhm_mm smoothing_fwhm_mm], spm_type('float32'));
    end
    volumes = spm_vol(model_input);
    if numel(volumes) ~= 224
        error('Run %02d has %d volumes, expected 224', run_index, numel(volumes));
    end
    rows = cell(224, 1);
    for volume_index = 1:224
        rows{volume_index} = sprintf('%s,%d', model_input, volume_index);
    end
    scan_lists{run_index} = char(rows);
end

SPM = struct();
SPM.xBF.name = 'hrf';
SPM.xBF.length = 32.0513;
SPM.xBF.order = 1;
SPM.xBF.T = 64;
SPM.xBF.T0 = 32;
SPM.xBF.UNITS = 'secs';
SPM.xBF.Volterra = 1;

for run_index = 1:10
    onsets = config.runs(run_index).onsets_seconds;
    names = config.runs(run_index).condition_names;
    if numel(onsets) ~= 60 || numel(names) ~= 60
        error('Run %02d does not have 60 trial conditions', run_index);
    end
    for trial_index = 1:60
        SPM.Sess(run_index).U(trial_index).name = {names{trial_index}};
        SPM.Sess(run_index).U(trial_index).ons = onsets(trial_index);
        SPM.Sess(run_index).U(trial_index).dur = 3;
        SPM.Sess(run_index).U(trial_index).P(1).name = 'none';
    end
    motion = readmatrix(config.runs(run_index).motion_txt, 'FileType', 'text');
    if ~isequal(size(motion), [224 6]) || any(~isfinite(motion), 'all')
        error('Run %02d motion matrix is not finite 224x6', run_index);
    end
    SPM.Sess(run_index).C.C = motion;
    SPM.Sess(run_index).C.name = {'X','Y','Z','x','y','z'};
    SPM.xX.K(run_index).HParam = 128;
end

SPM.nscan = repmat(224, 1, 10);
SPM.xY.P = cat(1, scan_lists{:});
SPM.xY.RT = 1.8;
SPM.xGX.iGXcalc = 'Scaling';
SPM.xVi.form = 'AR(1)';

original_directory = pwd;
cleanup_directory = onCleanup(@() cd(original_directory));
cd(output_dir);
SPM = spm_fmri_spm_ui(SPM);
if size(SPM.xX.X, 1) ~= 2240 || size(SPM.xX.X, 2) ~= 670
    error('Unexpected design shape %dx%d; expected 2240x670', size(SPM.xX.X,1), size(SPM.xX.X,2));
end
SPM = spm_spm(SPM);

beta_index = zeros(600, 1);
run = zeros(600, 1);
trial_in_run = zeros(600, 1);
spm_design_column = zeros(600, 1);
beta_file = strings(600, 1);
row = 0;
for run_index = 1:10
    for trial_index = 1:60
        row = row + 1;
        design_column = SPM.Sess(run_index).Fc(trial_index).i;
        if ~isscalar(design_column)
            error('Trial condition maps to multiple design columns');
        end
        beta_index(row) = row - 1;
        run(row) = run_index;
        trial_in_run(row) = trial_index;
        spm_design_column(row) = design_column;
        beta_file(row) = string(fullfile(output_dir, SPM.Vbeta(design_column).fname));
    end
end
trial_betas = table(beta_index, run, trial_in_run, spm_design_column, beta_file);
writetable(trial_betas, fullfile(output_dir, 'trial_beta_index.tsv'), 'FileType', 'text', 'Delimiter', '\t');

provenance = struct();
provenance.analysis_id = 'ai_iaps_sub04_spm_lsa_historical_model_v1';
provenance.config_path = config_path;
provenance.branch = config.branch;
provenance.smoothing_fwhm_mm = smoothing_fwhm_mm;
provenance.smoothing_location = 'pre-GLM BOLD';
provenance.spm_dir = spm('Dir');
provenance.spm_version = spm('Version');
provenance.spm_package_revision = 7771;
provenance.spm_spm_function_revision = 7738;
provenance.spm_git_commit = '3085dac00ac804adb190a7e82c6ef11866c8af02';
provenance.matlab_version = version;
provenance.design_rows = size(SPM.xX.X, 1);
provenance.design_columns = size(SPM.xX.X, 2);
provenance.n_trial_betas = height(trial_betas);
provenance.completed_at = char(datetime('now', 'TimeZone', 'local', 'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
fid = fopen(fullfile(output_dir, 'provenance.json'), 'w');
if fid < 0, error('Cannot create provenance.json'); end
fprintf(fid, '%s\n', jsonencode(provenance, PrettyPrint=true));
fclose(fid);
fprintf('SPM_LSA_COMPLETE branch=%s smoothing=%g output=%s\n', config.branch, smoothing_fwhm_mm, output_dir);
end
